### ISSUE TITLE
Bodhi updates are currently broken

### ISSUE THREAD

**Issue by ochosi** [osbuild/fedora-bot#41]
With the upgrade to Bodhi 6 our workflow to publish updates is broken. The kerberos ticket alone does not seem to suffice anymore, instead one needs to log in to accounts.fedoraproject.org and then copy-paste a token from the website to the terminal to be able to successfully authenticate.

There is a PR open to fix the problem and restore our current workflow: https://github.com/fedora-infra/bodhi/pull/4602

Until the above PR is merged, we will have to run `fedpkg update` manually to publish the updates after the Koji build has succeeded.

@ondrejbudai @thozza

**Comment by TomasTomecek** [comment]
Hey guys, just wanted to check if you actually tried to create an update locally via Bodhi 6 python client: authenticating and then running `bodhi_client.save(...)`. If so, did it work for you?

Because today I realized that even though I'm authenticated, the creation still fails on permission problems. I'm trying to understand where the problem exactly is.

**Comment by martinpitt** [comment]
In case you mean me in my role as reporter: I created the manual updates on the web UI, not the API. That worked fine.

**Comment by ochosi** [comment]
I've removed the Fedora password from the GitHub secrets to skip this bit of the workflow.

**Comment by TomasTomecek** [comment]
Bodhi 7 is out and it supports kerberos & oidc authentication: https://github.com/fedora-infra/bodhi/releases/tag/7.0.0

**Comment by ochosi** [comment]
This is handled by Packit now, so we can close this ticket.
